log_level: DEBUG
data:
  path-root: /path/to/data
  url-root: http://localhost:8000/data/
rest:
  url-root: http://localhost:8000/
geocoder: maptiler
chunk-size: 1k
climada-logo:
  link: https://wcr.ethz.ch/research/climada.html
  img-src: /static/climada_logo.png
repository_url: https://github.com/ChrisFairless/climada_calc_api_onlypostgres/
test:
  file: /path/to/tests/file
  format: jpg
  tmp: /path/to/tmp/file
datasets:
  tropical_cyclone: True
  extreme_heat: False
job:
  timeout: 72000
cache:
  timeout: 72000
defaults:
   units:
     temperature: "fahrenheit"
     speed: "miles per hour"
     distance: "miles"
     area: "square miles"
     currency: "dollars"
   image_format: "tif"
   api_parameters:
     scenario_name: "historical"
     scenario_year: 2020
     n_tracks: 10
     min_dist_to_centroids: 20
   data-license: "Attribution 4.0 International (CC BY 4.0)"
lock-timeout: 10  # minutes
database_mode: 'read'  # One of 'off' 'read' 'create' 'update' 'fail_missing'
