# Generated by Django 4.0 on 2022-10-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_api', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='func',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='job_hash',
            field=models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='result',
            field=models.JSONField(null=True),
        ),
    ]
